### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by ProfessorMinx** [N00byKing/PalWorld-ServerInjector#1]
Ive extracted it in the location specified. I run the exe and nothing happens.

Does it only work if you are running a dedicated server yourself?

**Comment by N00byKing** [comment]
The .exe will run the server itself. Where exactly did you extract the contents to, and what does the folder look like right now?

**Comment by N00byKing** [comment]
No, this is for use with a game server you have access to, either running locally or on a service which allows you to specify game files and executables.

**Comment by ProfessorMinx** [comment]
any plans to make something that could work how i ask?

**Comment by N00byKing** [comment]
I'm personally not working on something like this, and do not plan to, sorry
