### ISSUE TITLE
can not run in Windows Server 2022 Standard

### ISSUE THREAD

**Issue by Rain156** [N00byKing/PalWorld-ServerInjector#10]

**Comment by bluethunder1080** [comment]
for what its worth, i have a server 2019 VM that can run the palserver, but cannot run this injector, getting an error with OpenGL32.dll

i just spun it up with a win10 vm, and runs without issue

**Comment by N00byKing** [comment]
This might be caused by the GUI then. If you dont need the GUI, disable it in the UE4SS ini

**Comment by Rain156** [comment]
Sorry for replying so late.
I solved the problem of not being able to open it before, but then I encountered the error "Glfw Error 65542: WGL: The driver does not appear to support OpenGL".
I searched the Internet for related topics about this error, but all I got was that I need to update the graphics card driver.
But my server does not have a graphics card driver, how should I solve it?

> This might be caused by the GUI then. If you dont need the GUI, disable it in the UE4SS ini
