### ISSUE TITLE
VirtualAllocEx failed

### ISSUE THREAD

**Issue by yoku0206** [N00byKing/PalWorld-ServerInjector#14]
When i run PalServerInject.exe it give me this

Starting as: PalServer-Win64-Test-Cmd.exe
Started PalServer (suspended)...
VirtualAllocEx failed.

**Comment by N00byKing** [comment]
I think the server binary was renamed, could you check? Its in `<Server Folder>/Pal/Binaries/Win32/`

**Comment by yoku0206** [comment]
I don't have `Win32` folder only `Win64` in `<Server Folder>/Pal/Binaries/`

**Comment by N00byKing** [comment]
Sorry, thats what I meant

**Comment by yoku0206** [comment]
What should the name of that file be?

**Comment by N00byKing** [comment]
`PalServer-Win64-Test-Cmd.exe`

**Comment by yoku0206** [comment]
Oh I don't have this file, only `PalServer-Win64-Shipping.exe` and `PalServer-Win64-Shipping-Cmd.exe` in my folder

**Comment by N00byKing** [comment]
Yeah, looks like they changed the name.
Fixed this in the code, if you can you could compile the launcher yourself now. Otherwise, I'll do it tomorrow

**Comment by yoku0206** [comment]
Okay, I'll try it

**Comment by N00byKing** [comment]
I've updated the release
