### ISSUE TITLE
Everything injects and works but the mods wont work?!

### ISSUE THREAD

**Issue by RealityGamin** [N00byKing/PalWorld-ServerInjector#5]
I tried around 5 different mods, on my local game I can get them all to work but when injecting the palserver it doesn't seem to work at all. I cleared the cache, making a new world, and tried almost every method imaginable on the internet, the issue is there are no errors to work with just simply wont work. 

I wouldn't mind being charged a fee to get this working for me, I can provide my discord for easier communication as well.

![image](https://github.com/N00byKing/PalWorld-ServerInjector/assets/100086757/b665013c-0ca8-4133-91fd-f46f233a00b0)

![image](https://github.com/N00byKing/PalWorld-ServerInjector/assets/100086757/5c3da1b6-dfb7-4e57-99d3-dc4d24ec4f66)

**Comment by NoroHime** [comment]
i also notice that, looks not working anymore, injector looking not problem but mods not work

**Comment by NoroHime** [comment]
> i also notice that, looks not working anymore, injector looking not problem but mods not work

i guess game is updated so signatures is broken, i found 1.2.0 from pre release, now everything work fine!

**Comment by RealityGamin** [comment]
> > i also notice that, looks not working anymore, injector looking not problem but mods not work
> 
> i guess game is updated so signatures is broken, i found 1.2.0 from pre release, now everything work fine!

What do you mean, please share

**Comment by NoroHime** [comment]
> > > i also notice that, looks not working anymore, injector looking not problem but mods not work
> > 
> > 
> > i guess game is updated so signatures is broken, i found 1.2.0 from pre release, now everything work fine!
> 
> What do you mean, please share
just new release
https://github.com/N00byKing/PalWorld-ServerInjector/releases/tag/v1.2.0
